-- VHDL Entity work.elem_type2.symbol
--
-- Created:
--          by - Fran.UNKNOWN (DESKTOP-IVAGNN6)
--          at - 17:48:52 26/10/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY elem_type2 IS
   PORT( 
      C : OUT    bit
   );

-- Declarations

END elem_type2 ;

--
-- VHDL Architecture work.elem_type2.struct
--
-- Created:
--          by - Fran.UNKNOWN (DESKTOP-IVAGNN6)
--          at - 17:48:52 26/10/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY work;

ARCHITECTURE struct OF elem_type2 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL A : bit;
   SIGNAL K : bit;


   -- Component Declarations
   COMPONENT elem
   PORT (
      A : IN     bit;
      K : IN     bit;
      C : OUT    bit
   );
   END COMPONENT;
   COMPONENT signal_a_k
   PORT (
      A : OUT    bit;
      K : OUT    bit
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : elem USE ENTITY work.elem;
   FOR ALL : signal_a_k USE ENTITY work.signal_a_k;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : elem
      PORT MAP (
         A => A,
         K => K,
         C => C
      );
   U_0 : signal_a_k
      PORT MAP (
         A => A,
         K => K
      );

END struct;
