-- VHDL Entity work.generador_senales.symbol
--
-- Created:
--          by - Fran.UNKNOWN (DESKTOP-IVAGNN6)
--          at - 16:09:30 18/10/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY generador_senales IS
   PORT( 
      S1 : OUT    std_logic;
      S2 : OUT    std_logic
   );

-- Declarations

END generador_senales ;

--
-- VHDL Architecture work.generador_senales.struct
--
-- Created:
--          by - Fran.UNKNOWN (DESKTOP-IVAGNN6)
--          at - 16:23:02 18/10/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF generador_senales IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1                                        
   process
     constant t: time := 10 ns;
   begin
       for i in 0 to 4 loop
         S1 <= '0', '1' after 2 * t / 5;
         S2 <= '0', '1' after 2 * t / 5, '0' after 3 * t / 5;
         wait for t;
         S1 <= '1';
         S2 <= '1';
       end loop;
     wait;
   end process;
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   


   -- Instance port mappings.

END struct;
