version: "3"
volumes:
  owncloud_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /clusterfs/owncloud
services:
  owncloud:
    image: owncloud/server:10.13
    container_name: owncloud_server
    restart: always
    ports:
      - 8080:80
    environment:
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=Vc0910$$
      - OWNCLOUD_DB_HOST=10.0.16.50
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - owncloud_data:/mnt/data
  