version: '3.1'
# Lanza un stack con un container de wordpress
volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: /clusterfs/wordpress
      o: bind
services:
  wordpress:
    image: wordpress:5.8.3-php7.4-apache
    ports: 
      - 80:80
    volumes:
      - wordpress-data:/usr/share/wordpress/wp-content
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - WORDPRESS_DB_NAME:wordpress
      - WORDPRESS_DB_USER:wordpress
      - WORDPRESS_DB_PASSWORD:'Vc0910$$'
      - WORDPRESS_DB_HOST:10.0.16.50

    