version: '3.6'
volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.16.44,rw,nolock,soft,intr
      device: “:/clusterfs/docker”
networks:
  portainer:
    driver: overlay
services:
  server:
    image: docker.io/portainer/portainer-ce:2.11.0
    depends_on:
      - “agent”
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_SECRET: 90009000
    ports:
      - 9000:9000
      - 8000:8000
    networks:
      - portainer
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
      restart_policy:
        condition: any
  agent:
    image: docker.io/portainer/agent:2.11.0
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_SECRET: 90009000
      CAP_HOST_MANAGEMENT: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /etc/localtime:/etc/localtime
    networks:
      - portainer
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      restart_policy:
        condition: any