version: "3.1"
services:
  wekan:
    image: wekanteam/wekan:v3.77
    ports:
      - 9080:8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - MONGO_URL=mongodb://10.0.16.53:27017/wekan
      - ROOT_URL=http://10.0.31.199:9080/