-- VHDL Entity work.adder.symbol
--
-- Created:
--          by - Fran.UNKNOWN (DESKTOP-IVAGNN6)
--          at - 18:52:44 04/10/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY adder IS
   PORT( 
      a : IN     std_logic_vector;
      b : IN     std_logic_vector;
      y : OUT    std_logic_vector
   );

-- Declarations

END adder ;

--
-- VHDL Architecture work.adder.struct
--
-- Created:
--          by - Fran.UNKNOWN (DESKTOP-IVAGNN6)
--          at - 18:52:44 04/10/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF adder IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1
   y <= a +b;                          


   -- Instance port mappings.

END struct;
