-- VHDL Entity work.mux2.symbol
--
-- Created:
--          by - Fran.UNKNOWN (DESKTOP-IVAGNN6)
--          at - 17:49:15 04/10/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY mux2 IS
   PORT( 
      sel : IN     std_logic_vector;
      x1  : IN     std_logic_vector;
      x2  : IN     std_logic_vector;
      y   : OUT    std_logic_vector
   );

-- Declarations

END mux2 ;

--
-- VHDL Architecture work.mux2.struct
--
-- Created:
--          by - Fran.UNKNOWN (DESKTOP-IVAGNN6)
--          at - 17:49:15 04/10/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF mux2 IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1                                        
   y <= x1 when (sel = "0") else 
        x2 when (sel = "1") else
        "X";
   
   


   -- Instance port mappings.

END struct;
