-- VHDL Entity work.mux4.symbol
--
-- Created:
--          by - Fran.UNKNOWN (DESKTOP-IVAGNN6)
--          at - 18:26:23 04/10/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY mux4 IS
   PORT( 
      sel : IN     std_logic_vector (1 DOWNTO 0);
      x0  : IN     std_logic_vector;
      x1  : IN     std_logic_vector;
      x2  : IN     std_logic_vector;
      x3  : IN     std_logic_vector;
      y   : OUT    std_logic_vector
   );

-- Declarations

END mux4 ;

--
-- VHDL Architecture work.mux4.struct
--
-- Created:
--          by - Fran.UNKNOWN (DESKTOP-IVAGNN6)
--          at - 18:26:23 04/10/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF mux4 IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1                                        
   y <=  x0 when (sel = "00") else
            x1 when (sel = "01") else
            x2 when (sel = "10") else
            x3 when (sel = "11") else
            "X";


   -- Instance port mappings.

END struct;
